{% set name = "logging_exceptions" %}
{% set version = "0.1.9" %}
{% set sha256 = "e2d94aa02372389229a2eee2d5b985201b72cb1e860bf8cbee3209cbbc125819" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - logging_exceptions

about:
  home: https://github.com/Bernhard10/logging_exceptions
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: 'Self-logging exceptions: Attach log messages to exceptions and output them conditionally.'
  dev_url: https://github.com/Bernhard10/logging_exceptions
extra:
  recipe-maintainers:
    - lpantano
