{% set name = "logging_exceptions" %}
{% set version = "0.1.7" %}
{% set sha256 = "6453acb0d4e435866ee0869a77a5801e4fd16c0e7a803a3c74c53fb15b981c68" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - logging_exceptions

about:
  home: https://github.com/Bernhard10/logging_exceptions
  license: MIT
  license_family: MIT
  summary: 'Self-logging exceptions: Attach log messages to exceptions and output them conditionally.'
  dev_url: https://github.com/Bernhard10/logging_exceptions
extra:
  recipe-maintainers:
    - lpantano
