travis:
  secure:
    BINSTAR_TOKEN: j+gRR0Kku77NJuTeU2xBpfEwFSdY4EZEmBSfsYxEPqoID7yE4iopDeCANIAZlaQMhZ532tLBSp2WPgctbjCLA0UJKV6jyKgMk/P+0T/GZ1MfMa3ahc6q9YI5JMQ3ya9AOqBqeKwvAb8x2fV8aRY3VGppk4eqVja7UstL9ylpT3MMvzdvntM+Bp5rnf3TK78Wg8EgAt2/Mc6RoAGj8alEOXhffAin4YCCQKnyHhQ4O6RdlrX8C0oloORoa70pnrXIknlraz1wFazIweTIrHSZoJ5F1fPK7BphPpja+aDHqiiWQaP1gKBLxFhj7CBKzlfxyyuPTebl8FkepN/6PqBlZX9sQbtk8K0LEz3nkiK+tCJVuy87fzIfJeY2Zw/15ecvf14r1ArhxsXpc9DtWXqSjoph88MLZJ1t8hOaRl8WmbOGkdTYB5b+K+NX3bbbmTQKLv8+ik0dz2cn7hsnELDEalzvTdGN8RuwDNBLolLjt/+i4WYPM5I63t0cN2/3wsASoTZLFkxi5C2wez5PiWPAGr/t4YdDDyc46NdGzzB75/oeZEUQ61Vkzx400wq8Z0qmzrB/HiUILwb1ev2Snb8avQabcrBKrnEdSwjifIUwxj6KjKpHpt8wtgD531WSB3gz8DlojOODF/hKRTox5aUPhmrWAP7d9IndgT8UHeDqRDY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
