travis:
  secure:
    BINSTAR_TOKEN: xxlJBv6cWvl57I3unSeoKB1TgeY3qBu3Af8jde+QdTwQuKVtfnCFLGlL4zlFj8OpoQZJRNgBoHinFKXJsoX5E2lJ9SQNDjedUs6kRjFiBsh3w8hw/AWg72IsVQK1BvInAVQ+XC3tf+ncR3MYsiP6hnClmcBSx3EukrzB2lV+DIpy9vE920FjsevJFenmPHETReRP51Jr7xFr7cCQTH7sahg01ZDdvzr8wwhhj2JeCO4QoZw/OpQpA8Rrxp83Ftt97ta5Nbvk8sPARlv6XFVTXwNJfwWrebr/3UTEQCSA3K+nroz/NOZotYKZEGG+NvB4hPmxqdxB7OtSdSRIyj7S6KGcqcZR1vk4Ene7h7j9X4P+o7K1YmnenrfV0uhnXNZvy2hLuiZp4MRXzdmiIuBXa7jK510FO7SOggYTm1h27KigSRJuB8BaSSasYk3KrDw6PDH1KPHulKhRg08cIeaP1iHYPTT2sTmfSIq/FFzYgbIwY20kX5FU2BiEZDeX+mcCujnHV+KlohIxqI0OZMPOGZFDB50tXvpPDsGl3gjlGtKC1I42q7TOAHK8Wo4i8qZyktHfT2e05Ez0dsNRf+FSQ8iiaL7KnWtbtx45nQWyMK6BUHaOy6K9dF4Ptw1SZNTGRFtRN76BvH5weiQu1xJus5w9UtEpKVUnUryye0FxS48=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
