travis:
  secure:
    BINSTAR_TOKEN: lwC9aeMF/jpgQ7+CYtV0qUf9I8nIaK3xe62ie+LqCJmNDrz3vylvr4Nzs457k556ZKAqH+kjpWtxRmJYdSoJeA9UugxY6x9ocGINnFRjwz0+uR+kCYihNanCAkwb50S/gGCV+Ywqn2iT5a1LcCnaL6Jl6SN1ALutS75km28xe2E4BsvbSJo6rCXSdPFy1bT4loAST4q1hRJrX4pOrog0MY5wLpNEgGMpgaV7re5z/9GD2wdJpTzrDOS70ErkrgFKu9hVEt/2PD2HjEOpfQdBZTlhgHv+zQj8Qa4k7LzJSJh91rvcceKGDovd5wsIPf5B1o5tbx+V5XdfXj+TQQz+hCgZ/bT8GsWNrcxt44oFCHf6r+Vfo6LjxWzf96gyv1LBJ72j2mpmLRL0isYTKxW6Fm3tXnCDY79TcEaR38LN+7/UbEWLbePeg17ahR39MQSnQcUYd99PzT7nirKNf/ZcjoV57T4b1sN0IMpiWlSiZBrwPtPT0OBUzxu3A6kspe0cjCh0NzkRd47RxZZxFZBF3e/N0ekeIAQ7so84blaGTFIoml1rBvqYynp3z9X7uZ+os3x+9jMThSl7XmfLn2wTPxjGIlV/hW/D6mIOpqKfoGkkBxplE0FZ/5R0tTPaP7KKwp863SpJzKcX7i3Bz2Z1LWm3+zUW2TWE2qC5hn6n0EM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
