travis:
  secure:
    BINSTAR_TOKEN: Ww3RverpoK/wLvyWWylhOLAqHSW9tg1+FZAWBr8Dj+hho4SjGtoCRLqnIefSlaUVUBznZsQ6jjsP+QH+vuK3UMOsr2C2Gwak5/Nlu5lcOkoVMHhLmaAuraNAFt+J/I2x2bTl/VFJWnn9jvydgDRABrxXPn6GkU37qT8egOXAx2IBTyR4fpqIzVGJCKi6WvYPup1rChMTkc0z2zUO6E6c47gqWrYDxGhFEXgNOeBgm3SbM6TWSeM4hOwugHO7K77orQF9kw5LGTr2N40ld4S0P6osuQ2gMuDk0w27Mpth4qoGYbRDV8RQHSIJy2fmOvzCLN9EMEP4uPP4OD0e91GveMj0kn0Ga1aGOnFXfjDfOcZZfrJVVEmlobdumns0AuR5Na67d19d9SB8ryChsAL+Yewa2CumBUPY/Smj7Un93gYkdzwyIAcnmHx/WA6XXgyTINSxBSKK95rOM6b83cc3Q/OcKRepIX4H/W7r0hV3lS52WhK4f9km0QZssPOnvN0ay9HLrx8OBXcVqTBEDqguI5DeVzTnXCvAIhUmY1fSzazmZZoEY29yHWN1eU31V4ek3UHa3JsnkTm5EMjuMmrL1XIAImBiUhblYuG7nsHD4UCM/4dIFb4l73Tl5ZWY9EAE+SPAEL050D4RCjKFoqlIcshRiQiGwb4JqGz1QNgEmcQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
